version: '3.8'
services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sql123
      - MYSQL_DATABASE=event2all
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  server:
    build: .
    container_name: event2all-server
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
  frontend:
    build: ../event2allfrontend
    container_name: event2all-frontend
    volumes:
      - ../event2allfrontend/:/home/node/app
    ports:
      - 5173:5173
    depends_on:
      - server
    restart: always